### PR TITLE
Add tests for onOpen callback

### PR DESCRIPTION
**Pull request by evan-007**
cc @okize and @jslate 

https://jiraplm.atlassian.net/browse/SCHOONER-1148

Adds a test for the callback added in https://github.com/patientslikeme/react-aria-menubutton/pull/2, tests and linter are green.

I had to update one of the other tests because in the real library `manager.isOpen` is coupled to the component's `state.open` and they will both be the same boolean. The tests were using `mockManager` which did not update its `isOpen` when the menu was toggled. The test was setup with `manager.isOpen = false` and `state.open` false, but toggling the menu only updated `state.open = true` and not the manager so `manager.clearItems` was called even though the `open` state change was under test.

### CODE REVIEW

**Comment by jslate** [comment]
Took me a few minutes to re-familiarize, but looks good to me. I guess it is still an open goal to not be on this on_show_menu_callback_without_infinite_loop and to submit a pull request to davidtheclark/react-aria-menubutton. I guess maybe that's why you are adding a test? 👍

**Comment by evan-007** [comment]
Yeap, cleaning up and working towards a PR was the idea.

There was another ticket to add individual callbacks for each item in the plm-ui-component `ActionMenu`, but that behavior is tricky to test using this library. I'm trying to rewrite this library in ui components, but the a11y stuff is very hard to get right, so maybe in the meantime we should keep using this?

**Comment by okize** [comment]
@jslate @evan-007 grepping through plm-website I can only find 3 imports of ActionMenu and none of them use the `onOpenMenu` prop so do we even need this fork any more?

**Comment by evan-007** [comment]
@okize the upstream has that feature now as well: https://github.com/davidtheclark/react-aria-menubutton#openmenuwrapperid-openoptions, I played around using that version locally with ui-components and it's very easy to reimplement the work on this fork.

**Comment by okize** [comment]
@evan-007 ah ok, even better if there's no external dependencies. let's try to get off the fork which will make installs smoother.

**Comment by jslate** [comment]
Huh, you are right, we aren't using it. I think the thing that we were using it for is now hard coded as `openLeft`: https://github.com/patientslikeme/plm-website/blob/current/frontend/src/HealthJourney/ConditionInfoOptions.jsx#L132  

So yeah, get off the fork by all means.

**Comment by jslate** [comment]
Oh, we are using it here: https://github.com/patientslikeme/plm-ui-components/blob/master/src/components/ActionMenu/index.jsx#L76

Sorry, I'm probably just getting confused, maybe I'll come by and touch base...

**Comment by jslate** [comment]
I talked to @evan-007, I think we are 👍

**Comment by evan-007** [comment]
closing because we're using the upstream now

**Pull request closed without merging**
